spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/shopper/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**

  config:
    import: "optional:configserver:http://localhost:8088"



